name: PomlistIOS
options:
  createIntermediateGroups: true
  deploymentTarget:
    iOS: "17.0"
configs:
  Debug: debug
  Release: release
targets:
  PomlistIOS:
    type: application
    platform: iOS
    sources:
      - path: Sources
    settings:
      base:
        PRODUCT_NAME: Pomlist
        PRODUCT_BUNDLE_IDENTIFIER: me.0xpsyche.pomlist.ios
        SWIFT_VERSION: "5.9"
        IPHONEOS_DEPLOYMENT_TARGET: "17.0"
        INFOPLIST_FILE: Sources/Support/Info.plist
        GENERATE_INFOPLIST_FILE: "NO"
        ASSETCATALOG_COMPILER_APPICON_NAME: ""
        CODE_SIGN_STYLE: Automatic
        TARGETED_DEVICE_FAMILY: "1,2"
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
    scheme:
      gatherCoverageData: false
