name: PomlistIOS
options:
  minimumXcodeGenVersion: 2.38.0
  createIntermediateGroups: true
  deploymentTarget:
    iOS: "17.0"
configs:
  Debug: debug
  Release: release
settings:
  base:
    SWIFT_VERSION: "5.10"
targets:
  PomlistIOS:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: Sources
    settings:
      base:
        PRODUCT_NAME: Pomlist
        PRODUCT_BUNDLE_IDENTIFIER: me.0xpsyche.pomlist
        TARGETED_DEVICE_FAMILY: "1,2"
        INFOPLIST_FILE: Sources/Support/Info.plist
        GENERATE_INFOPLIST_FILE: NO
        CODE_SIGN_STYLE: Automatic
        CODE_SIGNING_ALLOWED: YES
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        ASSETCATALOG_COMPILER_APPICON_NAME: ""
        LD_RUNPATH_SEARCH_PATHS:
          - $(inherited)
          - "@executable_path/Frameworks"
    scheme:
      gatherCoverageData: false
      testTargets: []
